#!/usr/bin/env python3
"""Generate the strategy() build from the indicator so signal logic can never drift.
Re-run after any change to MovementEnginePro.pine."""
import re

src = open("MovementEnginePro.pine", encoding="utf-8").read()

# Derive the version from the indicator so the strategy can never advertise a
# stale one — it did read v3.5.6 while carrying v3.5.7 logic.
ver = re.search(r'indicator\("Movement Engine Pro ([^"]+)"', src).group(1)

# 1. indicator() -> strategy(). Risk-normalized sizing so stop distance does not
#    distort results: every trade risks the same % of equity.
src = re.sub(
    r'indicator\("Movement Engine Pro [^"]*"[^\n]*\)',
    'strategy("ME Pro Strategy %s", shorttitle="ME Pro ST", overlay=true, ' % ver +
    ''
    'max_boxes_count=500, max_lines_count=500, max_labels_count=500, max_bars_back=500, '
    'initial_capital=10000, currency=currency.NONE, '
    'default_qty_type=strategy.percent_of_equity, default_qty_value=10, '
    'commission_type=strategy.commission.percent, commission_value=0.02, slippage=2, '
    'process_orders_on_close=true, calc_on_every_tick=false)',
    src, count=1)

# 2. alertcondition() is indicator-only.
src = "\n".join(l for l in src.split("\n") if not l.lstrip().startswith("alertcondition("))

# 3. Risk input, placed with the other risk guards.
anchor = 'i_cooldown   = input.int(12,'
src = src.replace(anchor,
    'i_stRiskPct  = input.float(1.0, "STRATEGY: Risk Per Trade (% equity)", minval=0.05, maxval=10.0, step=0.05,\n'
    '     tooltip="Position size is derived from this and the entry-to-stop distance, so a wide-stop trade takes a smaller position and every trade risks the same fraction of equity. Without this, results would just measure stop width.",\n'
    '     group=G_RISK)\n' + anchor, 1)

src += '''
// ═══════════════════════════════════════════════════════════════════════════════
// STRATEGY EXECUTION (generated by build_strategy.py — do not hand-edit)
// ─────────────────────────────────────────────────────────────────────────────
// Entries/exits use the SAME buySignal/sellSignal and the SAME TP/SL levels the
// indicator draws, so the tester measures the engine rather than a re-statement
// of it. Scale-out is 33/33/34 across TP1/TP2/TP3, with the stop moved to
// breakeven after TP1 when that option is enabled.
//
// Fills are bar-close (process_orders_on_close), commission 0.02% and 2 ticks of
// slippage are charged. Intrabar order between stop and target is unknown to
// the tester on any bar that spans both — treat single-bar round trips with
// suspicion, and prefer results over many trades.
// ═══════════════════════════════════════════════════════════════════════════════

var float stEntry   = na
var float stSl      = na
var float stTp1     = na
var float stTp2     = na
var float stTp3     = na
var bool  stTp1Done = false
var int   stStartBar = na

stRiskDist = buySignal ? buyRiskDist : sellSignal ? sellRiskDist : na
stQty      = not na(stRiskDist) and stRiskDist > 0 ? (strategy.equity * i_stRiskPct / 100.0) / stRiskDist : na

if buySignal and not na(stQty)
    stEntry   := close
    stSl      := buySLpx
    stTp1     := buyTp1
    stTp2     := buyTp2
    stTp3     := buyTp3
    stTp1Done := false
    stStartBar := bar_index
    strategy.entry("Long", strategy.long, qty=stQty)

if sellSignal and not na(stQty)
    stEntry   := close
    stSl      := sellSLpx
    stTp1     := sellTp1
    stTp2     := sellTp2
    stTp3     := sellTp3
    stTp1Done := false
    stStartBar := bar_index
    strategy.entry("Short", strategy.short, qty=stQty)

// Breakeven after TP1 trades — mirrors the indicator's i_beAfterTp1 behavior.
if i_beAfterTp1 and not stTp1Done and strategy.position_size != 0 and not na(stTp1)
    tp1Touched = strategy.position_size > 0 ? high >= stTp1 : low <= stTp1
    if tp1Touched
        stTp1Done := true
        stSl      := stEntry

// Re-issued every bar so a breakeven move takes effect on the live orders.
if strategy.position_size > 0 and not na(stSl)
    strategy.exit("L1", from_entry="Long", qty_percent=33, limit=stTp1, stop=stSl)
    strategy.exit("L2", from_entry="Long", qty_percent=33, limit=stTp2, stop=stSl)
    strategy.exit("L3", from_entry="Long", qty_percent=34, limit=stTp3, stop=stSl)

if strategy.position_size < 0 and not na(stSl)
    strategy.exit("S1", from_entry="Short", qty_percent=33, limit=stTp1, stop=stSl)
    strategy.exit("S2", from_entry="Short", qty_percent=33, limit=stTp2, stop=stSl)
    strategy.exit("S3", from_entry="Short", qty_percent=34, limit=stTp3, stop=stSl)

// v3.5.8 time stop — mirrors the indicator's Max Bars In Trade.
if i_maxBars > 0 and strategy.position_size != 0 and not na(stStartBar) and (bar_index - stStartBar) >= i_maxBars
    strategy.close_all(comment="time stop")

// v3.5.23 invalidation exit — mirrors the indicator's rule so the backtest
// measures the same behaviour the chart draws. Position side is read from the
// strategy rather than the indicator's tradeBuy so the two can never drift.
var int stInvalidRun = 0
stInvalidLive = strategy.position_size > 0 ? (sellAligned >= i_invalidConf and buyAligned <= i_invalidOwn) : strategy.position_size < 0 ? (buyAligned >= i_invalidConf and sellAligned <= i_invalidOwn) : false
if barstate.isconfirmed
    stInvalidRun := stInvalidLive ? stInvalidRun + 1 : 0
if i_invalidExit and strategy.position_size != 0 and stInvalidRun >= i_invalidBars
    strategy.close_all(comment="invalidated")
    stInvalidRun := 0
'''

open("MovementEnginePro.strategy.pine", "w", encoding="utf-8").write(src)
print("wrote MovementEnginePro.strategy.pine")
